project:
  type: website
  output-dir: docs

website:
  title: "Caderno de aulas"
  page-navigation: true
  navbar:
    background: dark
    pinned: true
    left:
      - href: index.qmd
        text: "<i class='bi bi-info-circle-fill'></i> APRESENTAÇÃO"
      - href: Aula1.qmd
        text: "Aula 1"
      - href: Aula2.qmd
        text: "Aula 2"
      - href: Aula3.qmd
        text: "Aula 3"
      - href: Aula 4.qmd
        text: "Aula 4"
      - href: Aula5.qmd
        text: "Aula 5"
      - href: Aula6.qmd
        text: "Aula 6"
      - href: AulaMAPA.qmd
        text: "Aula de Mapa"

format:
  html:
    theme: lux
    toc: true
    toc-depth: 2
    toc-title: ""           
    css: styles.css
    include-in-header:
      - text: |
          <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    fig-width: 14
    fig-height: 9
    fig-align: center
    code-overflow: scroll
    echo: true
    warning: false
    message: false
    page-layout: full